### ISSUE TITLE
GridSearchCV

### ISSUE THREAD

**Issue by mak-rayate** [SAP-samples/hana-ml-samples#15]
Hello, 

I am looking for GridSearchCV in SAP HANA documents . I am not able to find the best_estimator_ attribute in this library. For example after using GridSearchCV  how do I know which attributes are get selected by the program and what is the accuracy for it. 

Can you please share documents where I can get idea of it. I already looked at SAP HANA [document ](https://help.sap.com/doc/1d0ebfe5e8dd44d09606814d83308d4b/2.0.06/en-US/hana_ml.algorithms.pal.html#hana_ml.algorithms.pal.model_selection.GridSearchCV)(not much useful)

**Comment by raymondyao** [comment]
Hi Mak,

The final result will be stored in `estimator` attribute. You can refer to this notebook. https://github.com/SAP-samples/hana-ml-samples/blob/main/Python-API/pal/notebooks/DiabetesClassificationHGBT.ipynb

**Comment by mak-rayate** [comment]
Thank you @raymondyao ! I will take a look on it. Thank you for guidance ...

**Comment by mak-rayate** [comment]
Hello @raymondyao , 

I have seen your refer notebook. I want to see the best select values by GridSearchCV. Do you know how to read `estimator` attribute. 
Thank You .

**Comment by raymondyao** [comment]
> Hello @raymondyao ,
> 
> I have seen your refer notebook. I want to see the best select values by GridSearchCV. Do you know how to read `estimator` attribute. Thank You .

It depends on the estimator that you use. For example, if you are using HGBT, the best parameter is the attribute selected_param_. We suggest you to use Unified Classification/Regression with specified function. So that you can use Unified Report to visualize your model.

**Comment by mak-rayate** [comment]
Hi , 

In my case I have used RandomForest classifier . What I have to do to see that attributes for RandomForestClassifier . 
It will be really helpful if you guide on it . 

Thank You.

![image](https://user-images.githubusercontent.com/67750027/146545130-bbf2892c-0d32-41a7-8abf-dc34be061816.png)

**Comment by raymondyao** [comment]
> Hi ,
> 
> In my case I have used RandomForest classifier . What I have to do to see that attributes for RandomForestClassifier . It will be really helpful if you guide on it .
> 
> Thank You.
> 
> ![image](https://user-images.githubusercontent.com/67750027/146545130-bbf2892c-0d32-41a7-8abf-dc34be061816.png)

Hi, 

We suggest to use the unified classification with model report. See the example below.
![image](https://user-images.githubusercontent.com/8198694/146548856-eb1a26a2-5abb-4a86-b49d-edebae01aab5.png)
Unfortunately, current PAL doesn't support the optimal parameter return for RDTClassifier and we recommend you to use HGBT instead.

**Comment by mak-rayate** [comment]
Hello , 

Thanks for instant support . As you mentioned I will definitely try it . Thanks once again !
