### ISSUE TITLE
RDTClassifier and Random Forest are same ? 

### ISSUE THREAD

**Issue by mak-rayate** [SAP-samples/hana-ml-samples#16]
Hello , 

RDT Classifier and Random Forest in SAP HANA ML package, are both same algorithms ? 
I have checked documentation of SAP , attributes in both algorithms looks like same for me, Can you also please confirm from your end as well . 
Currently I am trying to use Grid Search CV with unified classification but there is no option for Random Forest algorithm. Hence Raising this issue.

**Comment by raymondyao** [comment]
Please use RandomDecisionTree in unified classification. It works similar to random forest.
