### ISSUE TITLE
ERROR:hana_ml.algorithms.pal.unified_classification

### ISSUE THREAD

**Issue by mak-rayate** [SAP-samples/hana-ml-samples#17]
Hello , 

while using Grid Search CV with unified classification I am getting below error : 

ERROR:hana_ml.algorithms.pal.unified_classification:(423, 'AFL error: "HC_APL"."(DO statement)": line 65 col 1 (at pos 2182): search table error: _SYS_AFL.AFLPAL:UNIFIED_CLASSIFICATION_ANY: [423] (range 3) AFL error exception: exception 73001043: PAL error[73001043]:Value [0] of parameter TRY_NUM is invalid. \n')

I haven't declared any "TRY_NUM " variable in my code. Can you please tell me where I am doing wrong. 

code : 
`# train model with hyperparameter tunning
rfc = UnifiedClassification(func = 'randomforest')

gscv = GridSearchCV(estimator=rfc, 
                    param_grid={'n_estimators': [50,80,90,100,200,300,400,500,600,800],
                                'max_depth': [50, 60, 70, 80, 90, 100, 110,120,150],
                                'split_threshold': [0.1, 0.4, 0.7, 1],
                                'min_samples_leaf':[1,2,3,4]},
                    train_control=dict(fold_num=5,
                                       random_state=1,
                                       resampling_method='cv'), 
                    scoring='error_rate')

gscv.fit(data=hdf_train, key= 'CC_KEY', label='NAT_FUNCTION',partition_random_state=1,
         features=features,
         partition_method='stratified',
         stratified_column='class',
         build_report=True)
`

**Comment by raymondyao** [comment]
Would you mind sharing your HANA version and hana-ml version to me? The TRY_NUM looks like the old version... Now the parameter should be MAX_FEATURES... I cannot reproduce the issue from my HANA instance.

**Comment by mak-rayate** [comment]
SAP HANA Database version : 4.00.000.00.1634134105
hana_ml version : 2.10.21091803

**Comment by raymondyao** [comment]
Cloud you use `pip install -U hana-ml` to upgrade the package to 2.11?

**Comment by mak-rayate** [comment]
Thanks for response 
Yes , done ; now hana_ml version is as below . I have run the code , still getting same error as above. 
hana_ml version : 2.11.22010700

**Comment by raymondyao** [comment]
If you are using jupyter, have you restart the kernel?
If the problem still exists, maybe you can try to set max_features in the param_grid?

**Comment by mak-rayate** [comment]
--> yes I am using Jupyter Notebook and I restarted the kernel already. As per your suggestion I set max_features in param_grid ,still getting same error . 

--> I did GridSearchCV without unified classification , it works for me but with unified classification getting this error . In SAP there is no option to see the estimator values chosen by GridSearchCV if we are not using unified classification , am I right  

code: 
gscv = GridSearchCV(estimator=rfc, 
                    param_grid={'n_estimators': [50,80,90,100,200,300,400,500,600,800],
                                'max_depth': [50, 60, 70, 80, 90, 100, 110,120,150],
                                'split_threshold': [0.1, 0.4, 0.7, 1],
                                'min_samples_leaf':[1,2,3,4],
                                'max_features':[3,4]},
                    train_control=dict(fold_num=5,
                                       random_state=1,
                                       resampling_method='cv'), 
                    scoring='error_rate')

**Comment by raymondyao** [comment]
![image](https://user-images.githubusercontent.com/8198694/149305997-368f2f48-4452-46c6-b8ae-02dc7081097f.png)
I can run your code without error. I will do some investigation.

**Comment by raymondyao** [comment]
You can find your estimator under gscv.estimator.

**Comment by raymondyao** [comment]
Would you mind if you print(gscv.estimator.get_fit_execute_statement()) to me? So I can check the generated SQL.

**Comment by mak-rayate** [comment]
![image](https://user-images.githubusercontent.com/67750027/149311397-a4ab6661-34be-4fa3-b9a9-2df96c9d13eb.png)

For now I will go with only GridSearchCV (without unified classification) , If you find any fix for it please inform here and vise-versa. 
Thank You for your instant support

**Comment by raymondyao** [comment]
> ![image](https://user-images.githubusercontent.com/67750027/149311397-a4ab6661-34be-4fa3-b9a9-2df96c9d13eb.png)

I see. Could you print(conn.last_execute_statement)? conn is your connection context.

**Comment by mak-rayate** [comment]
> print(conn.last_execute_statement)

![image](https://user-images.githubusercontent.com/67750027/149312602-631b1e1e-f053-4333-b2ce-b07a5179e5e2.png)

that is really strange, I am able to connect the database and also able to fetch the data but but I can see "None" as output for last execute  statement

**Comment by raymondyao** [comment]
> > print(conn.last_execute_statement)
> 
> ![image](https://user-images.githubusercontent.com/67750027/149312602-631b1e1e-f053-4333-b2ce-b07a5179e5e2.png)
> 
> that is really strange, I am able to connect the database and also able to fetch the data but but I can see "None" as output for last execute statement

It only logged pal execution. Please use it after the fit.

**Comment by mak-rayate** [comment]
Hello , 

I think I got solution for TRY_NUM error . I am not sure for this but it works for me. Previously I was pushing less data to the algorithm (data size : 300 ),just to check the code . This time I have pushed large amount of data and now code is running without any error.
