### ISSUE TITLE
Can't append new data to existing table.

### ISSUE THREAD

**Issue by Joselguti** [SAP-samples/hana-ml-samples#22]
Hello,

I currently have a table to save data, the idea is that new data is constantly being introduced and saved/append to the last rows of said table.
Our team currently generates several indexes on this table:
![image](https://user-images.githubusercontent.com/38333642/160129935-bb45ef59-d156-48e2-ad72-10551ef427ca.png)

I'm currently dealing with two issues:

1. I currently have 4000 rows in the table, I'm adding 2000 new rows (with the same columns) via Pandas Dataframes, from Pandas I'm handling this new 6000 rows dataframe (old 4000+new 2000) and pushing it using the following code
`hana_ml.dataframe.create_dataframe_from_pandas(cc, df_upload, 'BUPRY', schema=schema, force=True, primary_key='INDEX')`

However with this the table gets dropped and a new one gets created with the new uploaded data, in this process the "INDEXES" also get cleaned up.

2.  I have been trying to not drop the table to prevent said "INDEXES" tab from getting cleaned, mainly playing with the two following parameters:

- force=False/True
- drop_exist_tab=False/True

When changing the value of these to both False I have noticed the following warning on the console
`Table already exists. Data will be appended to the existing table. To set "force=True" can empty the table.`
Which is the correct outcome I am looking for, however I am getting the following error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\bupryhr_dev\venv\lib\site-packages\hana_ml\dataframe.py", line 4658, in create_dataframe_from_pandas
    cursor.executemany(sql, rows)
hdbcli.dbapi.IntegrityError: (301, 'unique constraint violated')
```

I have been trying changing different parameters, uploading the total 6000 rows and just the 2000 new ones, not  specifying the primary key, but nothing seems to work and I keep getting the same error.

How can I fix this? Thanks in advance.

**Comment by raymondyao** [comment]
Hi, I saw you were using primary key. Please install the latest hana-ml (2.12) on PyPI and set upsert=True in create_dataframe_from_pandas function.

**Comment by Joselguti** [comment]
@raymondyao Works incredible, I didn't have knowledge about this parameter. 

Thank you a lot!
