### ISSUE TITLE
Parallel run

### ISSUE THREAD

**Issue by mak-rayate** [SAP-samples/hana-ml-samples#27]
Hi , 
Do we have anything option like in HGBT algorithm to execute parallel run in model training ? 
so Parallel runs will complete model training in minimum timestamp

**Comment by raymondyao** [comment]
Hi,

You can use thread_ratio to fit model in parallel.

    thread_ratio : float, optional
        The ratio of available threads used for training.

            - 0: single thread;
            - (0,1]: percentage of available threads;
            - others : heuristically determined.

**Comment by mak-rayate** [comment]
Hello [raymondyao](https://github.com/raymondyao), 
Thank you for your response !
If I put thread_ratio=0.7 that means ,will it creates 7 parallel execution in model training ? 
also unable to understand option "others : heuristically determined" , can you please explain ? 
Thank you .

**Comment by raymondyao** [comment]
0.7 thread_ratio will use 70% available threads in the instance. For example, if there're 10 free threads, then it will use 7.
Heuristically determined indicates that it will use auto-mode to decide the thread number.

**Comment by mak-rayate** [comment]
Thanks @raymondyao , clear now .

**Comment by mak-rayate** [comment]
Hi , 
I'm running hyperparameter tuning . Just can you please confirm that the thread ratio is defined in right way inside the code . 
My intention is to occupy all resource whatever we have that's why I gave thread ratio =1 . 

```from hana_ml.algorithms.pal.model_selection import RandomSearchCV
    rdt_params = dict(thread_ratio=1)
    rfc2 = UnifiedClassification(func = 'HybridGradientBoostingTree',random_state = 1,param_search_strategy='random',**rdt_params)
    rscv = RandomSearchCV(estimator=rfc2,
                        param_grid={'max_depth': [10,16,20,25],
                                    'n_estimators': [10,15,20,25,30],
                                   'learning_rate': [0.25,0.3,0.2,0.4,0.1]},
                        train_control=dict(fold_num=5,
                                           resampling_method='stratified_cv',
                                           random_state=1,
                                          random_search_times=2),
                        scoring='error_rate')```

**Comment by raymondyao** [comment]
Yes. You can simply add thread_ratio to unified_classification. 
hgbt = UnifiedClassification(func = 'HybridGradientBoostingTree', thread_ratio=1.0)
rscv = RandomSearchCV(estimator=hgbt ,
                                         param_grid={'max_depth': [10,16,20,25],
                                                               'n_estimators': [10,15,20,25,30],
                                                               'learning_rate': [0.25,0.3,0.2,0.4,0.1]},
                                         train_control=dict(fold_num=5,
                                                                       resampling_method='stratified_cv',
                                                                       random_state=1,
                                                                       random_search_times=2,
                                                                       param_search_strategy='random'),
                                         scoring='error_rate')

**Comment by mak-rayate** [comment]
Thank you @raymondyao for clearance !!
