### ISSUE TITLE
hana_ml.visualizers.model_debriefing.TreeModelDebriefing Issue 

### ISSUE THREAD

**Issue by mak-rayate** [SAP-samples/hana-ml-samples#32]
Hello , 
I have some doubts regarding model_debriefing in SAP HANA ml package as below : 
1) Can we perform model_debriefing on hybrid gradient boosting tree classification APL algorithm? also what about PAL ?
2) My intention is only I want to visualize the model , I mean how it works at backend while doing prediction , is it possible ?
3) I have tried using hana_ml.visualizers.model_debriefing on HGBT classification model (more interested on APL ). But some how it is not working . 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/67750027/233390816-90bd90d7-82a1-4000-b967-d3d505188308.png)

It will be really helpful if you share your points with us . 
Thank you !

**Comment by MarcDaniau** [comment]
Regarding the APL gradient boosting model, we provide shap values for the local explanation on predictions. A sample is provided here with some visualizations: https://blogs.sap.com/2021/12/08/shap-explained-models-with-automated-predictive-apl/
To your question, TreeModelDebriefing is not supported on APL models at the moment. Could you describe precisely what you would need in addition to shap values for explaining the predictions, so that I can capture the requirement for the APL team ?

**Comment by cmog** [comment]
The PAL algorithm is Hybrid Gradient Boosting Tree (HGBT) , a sample notebook for HGBT can be found here using the [TreeModelDebriefing](https://github.com/SAP-samples/hana-ml-samples/blob/main/Python-API/pal/notebooks/TreeModelDebriefing.ipynb).  In general for debriefing of PAL model, we recommend best to use the unified classification/regression interface, where a score method is available, debriefing model report and shapley debriefing visualizations incl. [force plots](https://help.sap.com/doc/cd94b08fe2e041c2ba778374572ddba9/2023_1_QRC/en-US/hana_ml.visualizers.html?highlight=force%20plot#hana_ml.visualizers.shap.ShapleyExplainer.force_plot). For PAL prediction explainability methods (Saabas / Shapley reason codes) see [here](https://help.sap.com/doc/cd94b08fe2e041c2ba778374572ddba9/2023_1_QRC/en-US/pal/topics/local_interpretability.html?highlight=saabas#local-interpretability-of-models). 
Hope this helps, best regards.
Christoph

**Comment by mak-rayate** [comment]
Thank you @MarcDaniau @cmog , I have noted your response, currently I'm going through the notes provided by you. 
For now purpose I'm closing it but @MarcDaniau regarding mentioned your question , if needed any additional requirement I will definitely mentioned it here.
